#!/bin/sh
. /lib/functions/uci-defaults.sh
board_config_update

case $(board_name) in
roceos,k50s)
    ucidef_set_interfaces_lan_wan "eth1 eth2 eth3 eth4" "eth0"
    ;;
*)
    ucidef_set_interfaces_lan_wan "eth1" "eth0"
    ;;
esac

board_config_flush
exit 0